# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hi! I'm Shavaun."
email: 'shavaun@victoriousninja.com'
description: "I'm a technical writer and I love to bring people together by solving communication problems."
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://shavaun.github.io/portfolio" # the base hostname & protocol for your site, e.g. http://example.com
github_username: 'shavaun'
linkedin_username: 'shavaunt'

# Buttons below intro
samples:
- jump_link: 'api_samples'
  text: 'API Samples'
- jump_link: 'user_guides'
  text: 'User Guide Samples'
- jump_link: 'sop_samples'
  text: 'SOP Samples'
- jump_link: 'other_samples'
  text: 'Developer Communication Samples'


# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 10
footer_text: '©2020 Shavaun Tesareski'
theme_source:
  theme_name: 'Phantom'
  theme_author: 'Jami Gibbs'
  theme_source_url: 'https://github.com/jamigibbs/phantom'

admin_name: 'Shavaun Tesareski'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }